### ISSUE TITLE
web端网页验证的问题

### ISSUE THREAD

**Issue by DonkeXu** [Allen7D/mini-shop-server#101]
我使用了mini-shop-server的后端，管理前端用的是lin-cms-vue-0.2.x，
遇到的问题是，登录后，获取需要权限的数据（@auth.login_required）提示“UNAUTHORIZED”，
我按照小程序里的格式添加了请求头也是无效的。
有什么解决方法吗？
axios.js:
```
        var header = {
          'content-type': 'application/json',
          'authorization': `Basic ${Base64.encode(`${accessToken}:$`)}`
        }
        reqConfig.headers = header
```

另外，请教一下，小程序请求头中为什么要base64encode呢？

**Comment by Allen7D** [comment]
1. 关于与lin-cms-vue-0.2.x适配的问题

lin-cms-vue-0.2.x的JWT接口认证是Bearer Token，而mini-shop-server的Basic Auth，两者，因此他们在前端和后端加密和解密的方式是不同的
你使用Postman这个接口测试软件就会发现。
![image](https://user-images.githubusercontent.com/15182982/84220956-a84d1980-ab06-11ea-9e11-a6fcc7a53e1d.png)

2. 关于小程序的请求头为何要Base64.encode加密

前端之所以要加密，是因为后端解析(代码在app)

**Comment by DonkeXu** [comment]
校验成功了，感谢！
