### ISSUE TITLE
想问下这个系统框图是用什么软件画的？

### ISSUE THREAD

**Issue by Valuebai** [Allen7D/mini-shop-server#28]
![arch](https://user-images.githubusercontent.com/9695113/59171744-16b76e80-8b77-11e9-9838-652f630e016f.png)

**Comment by Allen7D** [comment]
PPT就可以画，推荐使用 https://www.processon.com/diagrams

**Comment by Valuebai** [comment]
> PPT就可以画，推荐使用 https://www.processon.com/diagrams
thank you
