### ISSUE TITLE
raise BadRequest("Failed to decode JSON object: {0}".format(e))

### ISSUE THREAD

**Issue by DonkeXu** [Allen7D/mini-shop-server#85]
`req_body = request.get_json() if request.get_json() else {}`
这里报错（我是在小程序端调用）
`raise BadRequest("Failed to decode JSON object: {0}".format(e))`
那行加了try···except···后log输出
`    "path": {},
    "query": {},
    "body": {}
`
可能是request没有获得参数？

**Comment by Allen7D** [comment]
apply_request_log方式必须是debug模式下运行，线上直接使用会报错

请修改app/config/secure.py中配置项
DEBUG = False

在app/__init__.py就能正常运行
if app.config['DEBUG']:
    apply_request_log(app)  # 打印请求日志
